# Imagen base para Nginx
FROM nginx:latest

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 8080
EXPOSE 8080

# Comando para iniciar Nginx después de que la aplicación esté lista
CMD ["nginx", "-g", "daemon off;"]
