# Imagen base para la construcción
FROM node:14

# Instalación de npm y react
RUN apt-get update && \
    apt-get install -y npm && \
    npm install -g create-react-app

# Creación del directorio de la aplicación
WORKDIR /app

# Descarga del proyecto desde GitHub
RUN git clone https://github.com/AlexMendoza82s/AlbumMaker /app/AlbumMaker

# Cambio al directorio del proyecto
WORKDIR /app/AlbumMaker

# Instalación de las dependencias del proyecto
RUN npm install

# Comando para compilar la aplicación
RUN npm run build

# Comando para iniciar la aplicación en el puerto 3000
CMD ["npm", "start"]